# BukkitTelnet v3.0 Configuration File

# Port to bind to:
port: 8765

# Address to listen on, leave blank for all:
address: '108.170.15.242'

# Main connection password, must be defined:
password: 'KaneFreedomRoot121101'

# List of admins / IPs that don't have to use the password:
admins:
  taahanis:
    - 76.174.85.132
  _herobrian35_:
    - 209.164.167.58
  markbyron:
    - 71.47.67.103
